server:
  port: 12000


dubbo:
  application:
    name: shop-order-api
  protocol:
    name: dubbo
    port: 12001
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos

shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: http://192.168.88.128:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: admin
      password: 123456
  client:
    http:
      props:
        contextPath: /
        appName: order