server:
  port: 9000

dubbo:
  application:
    name: shop-cart-api
  protocol:
    name: dubbo
    port: 9001
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos