server:
  port: 8000

dubbo:
  application:
    name: shop-admin-api
  protocol:
    name: dubbo
    port: 8001
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos

shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: http://192.168.88.128:9095  #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: admin
      password: 123456
  client:
    http:
      props:
        contextPath: /admin
        appName: admin
logging:
  level:
    root: info
    org.springframework.boot: info
    org.apache.ibatis: info
    org.apache.shenyu: debug