server:
  port: 11001

dubbo:
  application:
    name: shop-product-api
  protocol:
    name: dubbo
    port: 11012
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos
