server:
  port: 9002

spring:
  datasource:
    druid:
      url:  jdbc:mysql://192.168.88.128:3306/shop_cart?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&zeroDateTimeBehavior=convertToNull
      driver-class-name:  com.mysql.cj.jdbc.Driver
      username:  root
      password:  root
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall
  redis:
    host: 192.168.88.128
    port: 6379

dubbo:
  application:
    name: shop-cart-rpc
  protocol:
    name: dubbo
    port: -1
    host: 0.0.0.0
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos

# 如果 这里配置了, 那么 common 就不要配置了, 不然会重复
# 而且,如果 common 中也存在 xml,就需要使用 classpath*
mybatis:
  mapper-locations: classpath*:mapper/*.xml
