version: "3.5"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: minio
    restart: always
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123456

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  
  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nacos
    depends_on:
      - mysql
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.88.128
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
    volumes:
      - ./nacos/logs:/home/nacos/logs
  shenyu-bootstrap:
    image: apache/shenyu-bootstrap:2.5.1
    container_name: shenyu-bootstrap
    ports:
      - "9195:9195"
    volumes:
      - ./shenyu-bootstrap/logs:/opt/shenyu-bootstrap/logs
      - ./shenyu-bootstrap/conf:/opt/shenyu-bootstrap/conf
      - ./shenyu-bootstrap/ext-lib:/opt/shenyu-bootstrap/ext-lib
    depends_on:
      - shenyu-admin
    environment:
      - shenyu.sync.websocket.urls=ws://192.168.88.128:9095/websocket
      - spring.main.allow-bean-definition-overriding=true
    healthcheck:
      test: [ "CMD", "wget", "http://192.168.88.128:9195/actuator/health" ]
      timeout: 2s
      retries: 30
  shenyu-admin:
    image: apache/shenyu-admin:2.5.1
    container_name: shenyu-admin
    depends_on:
      - mysql
    volumes:
      - ./shenyu-admin/logs:/opt/shenyu-admin/logs
      - ./shenyu-admin/conf:/opt/shenyu-admin/conf
      - ./shenyu-admin/ext-lib:/opt/shenyu-admin/ext-lib
    environment: 
      - SPRING_PROFILES_ACTIVE=mysql
      - spring.datasource.url=jdbc:mysql://192.168.88.128:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "9095:9095"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://192.168.88.128:9095/actuator/health | grep UP || exit 1" ]
      timeout: 2s
      retries: 30

  rocketmq-namesrv:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq-namesrv
    ports:
      - 9876:9876
    volumes:
      - ./rocketmq/namesrv/logs:/home/rocketmq/logs
      - ./rocketmq/namesrv/store:/home/rocketmq/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128M"
    command: sh mqnamesrv
    networks:
      - rocketmq

  rocketmq-broker-1:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq-broker-1
    ports:
      - "10911:10911"
    volumes:
      - ./rocketmq/broker/logs:/home/rocketmq/rocketmq-4.9.4/logs
      - ./rocketmq/broker/store:/home/rocketmq/rocketmq-4.9.4/store
      - ./rocketmq/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.9.4/broker.conf
    environment:
      TZ: Asia/Shanghai
      JAVA_OPT_EXT: "-server -Xms512m -Xmx512m -Xmn512m"
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.4/broker.conf  -n rocketmq-namesrv:9876 autoCreateTopicEnable=true &
    depends_on:
      - rocketmq-namesrv
    networks:
      - rocketmq
  rocketmq-broker-2:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq-broker-2
    ports:
      - "20911:20911"
    volumes:
      - ./rocketmq/broker1/logs:/home/rocketmq/rocketmq-4.9.4/logs
      - ./rocketmq/broker1/store:/home/rocketmq/rocketmq-4.9.4/store
      - ./rocketmq/broker1/conf/broker.conf:/home/rocketmq/rocketmq-4.9.4/broker.conf
    environment:
      TZ: Asia/Shanghai
      JAVA_OPT_EXT: "-server -Xms512m -Xmx512m -Xmn512m"
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.4/broker.conf -n rocketmq-namesrv:9876 autoCreateTopicEnable=true &
    depends_on:
      - rocketmq-namesrv
    networks:
      - rocketmq

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    container_name: rocketmq-dashboard
    ports:
      - 8180:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    depends_on:
      - rocketmq-namesrv
    networks:
      - rocketmq


networks:
  rocketmq:
    name: rocketmq
    driver: bridge