dts:
  # 快鸟物流查询配置
  express:
    enable: true
    appId: "xxxxxx"
    appKey: "xxxxxx"
    vendors:
      - code: "HTKY"
        name: "百世快递"
      - code: "YZBK"
        name: "邮政国内标快"
      - code: "ZTO"
        name: "中通快递"
      - code: "YTO"
        name: "圆通速递"
      - code: "YD"
        name: "韵达速递"
      - code: "YZPY"
        name: "邮政快递包裹"
      - code: "EMS"
        name: "EMS"
      - code: "DBL"
        name: "德邦快递"
      - code: "FAST"
        name: "快捷快递"
      - code: "ZJS"
        name: "宅急送"
      - code: "TNT"
        name: "TNT快递"
      - code: "UPS"
        name: "UPS"
      - code: "DHL"
        name: "DHL"
      - code: "FEDEX"
        name: "FEDEX联邦(国内件)"
      - code: "FEDEX_GJ"
        name: "FEDEX联邦(国际件)"
  #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: true
      host: smtp.aliyun.com
      username: dtsshop@aliyun.com
      password: xxx
      sendfrom: xxx@aliyun.com
      sendto: xxx@qq.com

    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: false
      appid: 1400286323
      appkey: 223123sade14c129c4ce9a30b5f90ad2c
      template:
        - name: paySucceed
          templateId: 112233
        - name: captcha
          templateId: 112233
        - name: ship
          templateId: 112233
        - name: refund
          templateId: 112233

    # 微信模版通知配置
    # 微信模版用于通知客户或者运营者，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    wx:
      enable: false
      template:
        - name: paySucceed
          templateId: sirUcgTAIQfoIxxxxxx
        - name: captcha
          templateId: OfBkXh7UILpsDkcxxxxxx
        - name: ship
          templateId: dqTuWzrmL_wwK-SJsxxxxxx
        - name: applyRefund
          templateId: lzPHltMpUOiBol7i2Yxxxxxx
        - name: refund
          templateId: NDy6EpPuu2C9NMUxxxxxx
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: dts/storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8080/demo/storage/

server:
  port: 9000

spring:
  datasource:
    druid:
      url:  jdbc:mysql://192.168.88.128:3306/shop_common?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&zeroDateTimeBehavior=convertToNull
      driver-class-name:  com.mysql.cj.jdbc.Driver
      username:  root
      password:  root
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall
  redis:
    host: 192.168.88.128
    port: 6379

dubbo:
  application:
    name: shop-third
  protocol:
    name: dubbo
    port: 9090
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos

# 如果 这里配置了, 那么 common 就不要配置了, 不然会重复
# 而且,如果 common 中也存在 xml,就需要使用 classpath*
mybatis:
  mapper-locations: classpath*:mapper/*.xml
