dts:
  #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: true
      host: smtp.exmail.qq.com
      username: 2407411399@qq.com
      password: qwer20011213
      sendfrom: 2407411399@qq.com
      sendto: 2463628602@qq.com