server:
  port: 10000


dubbo:
  application:
    name: shop-coupon-api
  protocol:
    name: dubbo
    port: 10001
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos
