dts:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: wxd96e4c5f61853416
    app-secret: ed6c8cb4dca7558d81b55a083724b48b
    mch-id: 1538666666
    mch-key: 1538xxxxxx-1538xxxxxx-1538xxxxxx
    notify-url: https://test.dtsshop.com/demo/order/dtsNotify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx

pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql
#  redis 配置
spring:
  redis:
    host: 192.168.88.128
    port: 6379
