server:
  port: 17000

dubbo:
  application:
    name: shop-user-api
  protocol:
    name: dubbo
    port: 17001
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos
