server:
  port: 14000


dubbo:
  application:
    name: shop-search-api
  protocol:
    name: dubbo
    port: 14001
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos
