server:
  port: 11000


dubbo:
  application:
    name: shop-groupon-api
  protocol:
    name: dubbo
    port: 11001
  registry:
    address: nacos://192.168.88.128:8848
    username: nacos
    password: nacos
